check all filtered row
frappe/datatable pull request #131
Opened 2021-04-20 12:28 UTC by dogansalman

2021-10-01 18:56 UTC, guilmori commented
Any plan to merge ?
I need the check all to only select filtered rows.

2022-09-15 21:37 UTC, JulioJair approved these changes

2022-09-22 12:26 UTC, JulioJair requested changes
window.datatable.datamanager does not work

2023-01-25 11:45 UTC, shariquerik commented
Duplicate PR https://github.com/frappe/datatable/pull/161

2023-01-25 11:45 UTC, closed without merging